"""add_slug_to_tag

Revision ID: 35507e263023
Revises: 40dc950ab97a
Create Date: 2026-08-27 13:34:31.044442

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35507e263023"
down_revision: str | None = "40dc950ab97a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("slug", sa.String(), nullable=False))
    op.create_index(op.f("ix_tags_slug"), "tags", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tags_slug"), table_name="tags")
    op.drop_column("tags", "slug")
    # ### end Alembic commands ###
