"""add_screenshot_key

Revision ID: 86012fac325e
Revises: 35507e263023
Create Date: 2026-08-27 14:37:42.367818

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86012fac325e"
down_revision: str | None = "35507e263023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookmarks", sa.Column("screenshot_key", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookmarks", "screenshot_key")
    # ### end Alembic commands ###
